# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

# Symbolic link to Arduino installation directory - see below
ARDUINO_DIR   =C:/Users/marti/Documents/Arduino
ARDMK_DIR = ./Arduino-Makefile
MONITOR_PORT  = com3
BOARD_TAG     = uno

USER_LIB_PATH = ./libraries
ARDUINO_LIBS = TinyGPSPlus AltSoftSerial

include ./Arduino-Makefile/Arduino.mk
